### ISSUE TITLE
Path for selenium

### ISSUE THREAD

**Issue by kstephensen** [joeyism/linkedin_scraper#132]
Hey can someone walk through this step? 

Where does this go?

export CHROMEDRIVER=~/chromedriver

**Comment by datatalking** [comment]
This looks like it needs to be entered into the terminal or a "output to Linux" type event.

Can you be more specific as to where you got this or what step this refers to?

**Comment by kstephensen** [comment]
![Screen Shot 2022-08-17 at 9 19 14 AM](https://user-images.githubusercontent.com/46613273/185191466-79d3e2c7-7fd4-459e-8de8-da37a63f0085.png)

It comes from the "Set Up" step. I'm using a Mac

**Comment by danielhangan** [comment]
1. Find what chrome version you have installed on your computer.
2. Go to https://pypi.org/project/chromedriver-py/#history and install the same version of chromedriver
3. And then
```python
from selenium import webdriver
import chromedriver_binary
driver = webdriver.Chrome()
```

P.S. I think you have to pip install chromedriver_binary --no-cache-dir
