### ISSUE TITLE
Open to work feature

### ISSUE THREAD

**Issue by mattfromboston** [joeyism/linkedin_scraper#137]
Following up on this same message I sent you on LinkedIn.-  I want to search for people and message people that list on their LinkedIn profile "open to work".  You can see on my profile this "open to work" feature surrounding my photo. The only way to search for "open to work" people with LinkedIn is to purchase their "recruiter" plan which is about $1100 per month. Can your scraper do this?  Best-Matt

**Comment by joeyism** [comment]
@mattfromboston was this what you're thinking of?
![Screenshot from 2022-11-15 12-51-17](https://user-images.githubusercontent.com/7503144/201913231-c2c858a9-1cc7-4b6d-b091-df8481609cae.png)

**Comment by mattfromboston** [comment]
Thank you for the response.  My apologies if my response is not very clear-I am not very technical

I want to be able to message people that have chosen to put on their Linkedin settings that they are "open to work".  When they do this setting the "open to work" verbiage appears around their profile.  Please see attached visual

In a perfect world would like to be able to download all of this into an excel spreadsheet and filter all these "open to work" people by geographic location and job title.  Best-Matt

![FireShot Capture 077 - (18) Daniel B  - LinkedIn - www linkedin com](https://user-images.githubusercontent.com/29707389/201915934-7fdda388-44b4-4154-867f-12507b6a6c66.png)

**Comment by mattfromboston** [comment]
Hi Joey-  If I could get a response to my previous comment when you get a moment

**Comment by joeyism** [comment]
There's enough in the tool for you to find and scrape people, but unfortunately the scraping results is not a part of the open sourced project. I've added `open to work` results in `2.11.0`, which you can get from `person.open_to_work` as a boolean
