### ISSUE TITLE
Data not scraped

### ISSUE THREAD

**Issue by Nesslax** [joeyism/linkedin_scraper#14]
Hey, 
the script don't scrape website, company size and all thouse informations. 

I don't know why but i can get the description 
here is an exemple 
<img width="1583" alt="capture d ecran 2018-07-16 a 22 46 20" src="https://user-images.githubusercontent.com/16743265/42784944-024e79da-8951-11e8-939e-8c6cfdfdc3c5.png">

**Comment by joeyism** [comment]
It may not be displayed, but it may still be stored in the object. Have you checked that?
