### ISSUE TITLE
When I tried to run it to scrape my own profile it just returned blanks for the experience and education

### ISSUE THREAD

**Issue by LukeHerbst** [joeyism/linkedin_scraper#143]
Firstly, great package. Hope I can get it to work. 

This was my code:

driver = webdriver.Chrome(ChromeDriverManager().install())
email = "xxxxx"
password = "xxxxx"
actions.login(driver, email, password) # if email and password isnt given, it'll prompt in terminal
person = Person("https://www.linkedin.com/in/luke-herbst/",scrape =True, driver=driver)
print(person.experiences ,person.educations )

it returned [] []

I used the chromedrivermanager because that has a workaround for Chromedriver and my Chrome browser not having coompatible

**Comment by dmzoneill** [comment]
same here

**Comment by joeyism** [comment]
Is it still like that? Latest release should've fixed that
