### ISSUE TITLE
Person Object Scraping all NULLs

### ISSUE THREAD

**Issue by Jfromtheroc** [joeyism/linkedin_scraper#144]
The person object mapping seems to be bringing up complete nulls. Linkedin may have remapped.

**Comment by WaleedAlfaris** [comment]
Same issue here. I get the Name, but all other fields return empty lists.

**Comment by teddsords** [comment]
Having the same issue here. Receiving empty lists ('[]')

**Comment by joeyism** [comment]
Is it still like that? Newest release should've fixed that

**Comment by sm-ak-r33** [comment]
Still nulls
