### ISSUE TITLE
Scraper times out when using AWS ec2 instance or GCP VM but works well on my personal computer

### ISSUE THREAD

**Issue by Arafatk** [joeyism/linkedin_scraper#177]
I am running this script 

```

from linkedin_scraper import Person, actions
import linkedin_scraper

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
print(linkedin_scraper.__file__)

options = Options()
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")
driver = webdriver.Chrome(options=options)

email = "some_email"
password = "some_password"
actions.login(driver, email, password) # if email and password isnt given, it'll prompt in terminal

person = Person("https://www.linkedin.com/in/joey-sham-aa2a50122", driver=driver)
print(person)
```

This script works well on my macbook. However when I run the same script through EC2 instance or through GCP vms in both cases it times out at this line 

https://github.com/joeyism/linkedin_scraper/blob/3a54a16809c6064efe8c566b5b8eb06f82c85c6d/linkedin_scraper/actions.py#L38

Now even after resetting the timeout to 200 seconds it waits for 200 seconds and then times out. What do I do about this? 

The only silver lining I saw is that on gcp vm atleast I get a verification code sent to my email. Can you folks help me out with this?

**Comment by joeyism** [comment]
Yea this is likely due to login issue by linkedin, where they need you to complete some captcha or something, to prevent scraping. Can you confirm it by letting me know which page it's on before it times out?

**Comment by Arafatk** [comment]
You are right. 

I added this debugging 

```
    try:
        element = WebDriverWait(driver, timeout).until(EC.presence_of_element_located((By.CLASS_NAME, c.VERIFY_LOGIN_ID)))
    except TimeoutException as ex:
        print("Exception has been thrown. " + str(ex))
        print(driver.page_source)
        driver.save_screenshot('screenshot.png')

```

Now this is the screenshot that i got 


<img width="594" alt="image" src="https://github.com/joeyism/linkedin_scraper/assets/11155207/15b627cb-2be2-4246-8631-7026e2922e63">


Now I am applying two different ways to solve this
1. Logging in on my computer and exporting the cookies and try to login from them in the ec2 instance
2. Logging in on my ec2 instance using either a terminal browser or some other technique to "verify" the ec2 instance. Let's see how that goes

**Comment by Arafatk** [comment]
I solved the problem by doing a VNC connection. Installing Chrome and then logging into linkedin by solving the captha. Now I think my ec2 instance is "validated" coz they also sent me a code on gmail etc. 

So now I was able to use it. 

Thanks @joeyism for the brilliant work

**Comment by Arafatk** [comment]
Added a PR -> https://github.com/joeyism/linkedin_scraper/pull/180

**Comment by joeyism** [comment]
Thanks for the PR. Merged

**Comment by PaulchauvinAI** [comment]
@arafatkatze I think I did not understand fully. Did you  need to "validate" the IP address of your ec2 instance by logging in into linkedin first ? On my side I don't even see the captcha when trying to access a person from the ec2. I get this: ![image](https://github.com/joeyism/linkedin_scraper/assets/97964230/51f994cc-27d9-4170-a520-24970894e88f)
