### ISSUE TITLE
Chromedriver

### ISSUE THREAD

**Issue by yangsh49** [joeyism/linkedin_scraper#18]
Hi joeyism,

Could you kindly explain more about: "export CHROMEDRIVER=~/chromedriver"? It will be really helpful for a beginner like me.

Thank you so much!
Shen

**Comment by ernests** [comment]
In short - it allows your small scraper script find Chromedriver.

Longer discussion about _export_ on Stackoverflow - https://stackoverflow.com/questions/13795237/what-does-the-export-command-do

**Comment by joeyism** [comment]
I also wrote a library that allows you to download a chromedriver if not exist locally: https://github.com/joeyism/autochromedriver
