### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by pl4g4** [joeyism/linkedin_scraper#19]
I followed the instructions 

 `pip3 install --user linkedin_scraper` 

and created a file 

`from linkedin_scraper import Person
person = Person("https://www.linkedin.com/in/andre-iguodala-65b48ab5")`

python version 

`Python 2.7.15rc1`

but im getting the error 

`Traceback (most recent call last):
  File "./linkedin_scraper_1.py", line 6, in <module>
    from linkedin_scraper import Person
ImportError: cannot import name Person
`

after i run `pip freeze` i get `linkedin-scraper==2.3.0`.... its installed. am I missing something?

**Comment by joeyism** [comment]
`pip3` installs it in python3. If you want it in python2, install it using `pip2`

**Comment by pl4g4** [comment]
Hi, using python3 i get errors because of print not using (), but python2 worked. 

Im now getting problem with selenium.

**Comment by joeyism** [comment]
If you're printing in python3, you must use brackets.

Can you copy and paste your code and the errors you're getting?
