### ISSUE TITLE
NUMB QUESTION AND NOT AN ISSUE, PLEASE HELP

### ISSUE THREAD

**Issue by Crewxx** [joeyism/linkedin_scraper#21]
I followed all procedures and scraping was done successfully as the Chrome closed on its own after scraping but I have no idea on how I could retrieve the scraped data. Please don't descend on me with anger because I am new on this data scraping and I really want to learn, please help me out.
HOW DO I RETRIEVE SCRAPED DATA, POSSIBLY SAVE AS .CSV FILE?

I have actually gone through the earlier issues before posting but non relate to my newbie questions.
Thanks and honestly I admire your works.

**Comment by joeyism** [comment]
To scrape the data, you can run something like

```python
from linkedin_scraper import Person
person = Person("https://www.linkedin.com/in/andre-iguodala-65b48ab5")
```

There's no direct mapping to a csv, since the scraped data is unstructured. If you know exactly which field you want, you can loop over the objects and put the values into a csv file one by one.

**Comment by Crewxx** [comment]
OK, THANKS
