### ISSUE TITLE
HTML update on /experience causes issue

### ISSUE THREAD

**Issue by beattymg** [joeyism/linkedin_scraper#219]
Hi,

It looks like Linkedin updated the layout for details/experience/ pages. This causes errors in 'get_experience' on the Person object.

There is no longer a 'pvs-list' element and that inner html logic breaks now. There is an outer 'pvs-list__container' element and the inner html has changed too.

**Comment by Nuung** [comment]
same issue 🫡

**Comment by beattymg** [comment]
@joeyism are you still working on this project? I could make a fix but just want to make sure it could get merged in. Thanks!

**Comment by JackBlair87** [comment]
I had the same issue. Outlined my experiences here: https://medium.com/@jackblair87/writing-a-live-follower-count-python-program-for-my-website-5e34631582d3

**Comment by axblueblader** [comment]
I made a working PR you can check out: https://github.com/joeyism/linkedin_scraper/pull/220

**Comment by paulomei** [comment]
> I made a working PR you can check out: #220

Thanks! This solved for me, so working as of 24 Jun
