### ISSUE TITLE
Is user linkedin_scraper still in use?

### ISSUE THREAD

**Issue by Marilynxingxing** [joeyism/linkedin_scraper#222]
Hi Joey

Is the linkedin_scraper still in use? When I run the code, it always shows as below
 raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
        GetHandleVerifier [0x00007FF72C7C9642+30946]
        (No symbol) [0x00007FF72C77E3D9]
        (No symbol) [0x00007FF72C676FDA]
        (No symbol) [0x00007FF72C6C822C]
        (No symbol) [0x00007FF72C6C850C]
        (No symbol) [0x00007FF72C70DCB7]
        (No symbol) [0x00007FF72C6ECAAF]
        (No symbol) [0x00007FF72C70B041]
        (No symbol) [0x00007FF72C6EC813]
        (No symbol) [0x00007FF72C6BA6E5]
        (No symbol) [0x00007FF72C6BB021]
        GetHandleVerifier [0x00007FF72C8FF84D+1301229]
        GetHandleVerifier [0x00007FF72C90BDC7+1351783]
        GetHandleVerifier [0x00007FF72C902A13+1313971]
        GetHandleVerifier [0x00007FF72C7FDD16+245686]
        (No symbol) [0x00007FF72C78759F]
        (No symbol) [0x00007FF72C783814]
        (No symbol) [0x00007FF72C7839A2]
        (No symbol) [0x00007FF72C77A3FF]
        BaseThreadInitThunk [0x00007FFEAFF926BD+29]
        RtlUserThreadStart [0x00007FFEB0EADFB8+40]

I am not sure what is going on. Could you please give me some instructions？

Sincerely
Marilyn

**Comment by ramzz** [comment]
I faced the same issue trying to use it locally from windows machine

**Comment by MACKNUS-INC** [comment]
Same here. I believe the code is not updated to retrieve the right classes and therefore throws an error.

**Comment by joeyism** [comment]
Just updated, see if this works
