### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by Kik099** [joeyism/linkedin_scraper#226]
from linkedin_scraper import Person, actions
driver = webdriver.Chrome( options=chrome_options)

email = "email"
password = "pass"
actions.login(driver, email, password) # if email and password isnt given, it'll prompt in terminal
person = Person("https://www.linkedin.com/in/andre-iguodala-65b48ab5", driver=driver)

And this error appears
`---------------------------------------------------------------------------
NoSuchElementException                    Traceback (most recent call last)
[<ipython-input-13-c4b5f8fd7641>](https://localhost:8080/#) in <cell line: 6>()
      4 email = "email"
      5 password = "pass"
----> 6 actions.login(driver, email, password) # if email and password isnt given, it'll prompt in terminal
      7 person = Person("https://www.linkedin.com/in/andre-iguodala-65b48ab5", driver=driver)

3 frames
[/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py](https://localhost:8080/#) in check_response(self, response)
    227                 alert_text = value["alert"].get("text")
    228             raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
--> 229         raise exception_class(message, screen, stacktrace)

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="remember-me-prompt__form-primary"]"}
  (Session info: chrome=130.0.6723.69); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:`

**Comment by Kik099** [comment]
Sorry it is working now

**Comment by madhusudhan123-star** [comment]
@Kik099 Hi I need help. this is my LinkedIn profile https://www.linkedin.com/in/madhu-sudhan-232089220/  waiting for your reply
