### ISSUE TITLE
no such element: Unable to locate element

### ISSUE THREAD

**Issue by trinanjan12** [joeyism/linkedin_scraper#26]
I used the code someone uploaded
**I noticed if the profile name is something like abcfss1 then it works fine. If the profile name  is like
 abc_fss_1 then it shows the below error
for example if my profile is https://www.linkedin.com/in/trinanjan_saha_216751116/ it doesn't work.
**

> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".pv-top-card-v3"}
  (Session info: chrome=77.0.3865.90)
![Screenshot from 2019-09-22 13-55-05](https://user-images.githubusercontent.com/27989326/65384493-a822a900-dd40-11e9-9c3d-ef92b3c11dc2.png)

**Comment by joeyism** [comment]
I think your url is wrong for your profile. I can't even access your profile through the browser

**Comment by trinanjan12** [comment]
The correct link should be [ https://www.linkedin.com/in/trinanjan-saha-216751116/](url)
I tested with the same link. The scraper shows the same error.

**Comment by MPocahontas** [comment]
Have the same error but with another selector when i try to scrape https://www.linkedin.com/in/hanna-krautsova-832720157/, for example. Error: "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".pv-entity__secondary-title"}".
I use login first.

**Comment by RitRa** [comment]
I'm having issues too:

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".pv-entity__secondary-title"}

**Comment by jdmin445** [comment]
linkedin has just changed their source code... we have to update every selectors....

**Comment by joeyism** [comment]
This should be fixed now. I've updated the README to show how to do it with login
