### ISSUE TITLE
Keeps refreshing last page of employee scrape

### ISSUE THREAD

**Issue by Quackerz** [joeyism/linkedin_scraper#31]
I'm trying to scrap a list of employees, but when it reaches the last page it will keep looping through it and never complete.

It looks like it has to with the loop continuing while the next element exists. It becomes unclickable on the last page, however.

**Comment by DavidCuentasMar** [comment]
Can you send a company url? I'm trying with google (https://www.linkedin.com/company/google) and I get the following message in terminal:

selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button aria-label="Next" id="ember273" class="artdeco-pagination__button artdeco-pagination__button--next artdeco-button artdeco-button--muted artdeco-button--icon-right artdeco-button--1 artdeco-button--tertiary ember-view">...</button> is not clickable at point (789, 204). Other element would receive the click: <span class="msg-conversation-card__pill t-14 t-black t-bold pr1">...</span>

**Comment by ActivateDZA** [comment]
> Can you send a company url example? I'm trying with google (https://www.linkedin.com/company/google) and I get the following message in terminal:
> 
> selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element ... is not clickable at point (789, 204). Other element would receive the click: ...

Hi

Make sure that your Chrome browser is running in maximize mode that is how I "fixed" this issue.

**Comment by brywhit** [comment]
I'm having a similar issue. I maximized my window but it was still stuck on the last employees page. I'm using my companies page (https://www.linkedin.com/company/3611445).

**Comment by joeyism** [comment]
Okay, this should be fixed in [2.4.5](https://github.com/joeyism/linkedin_scraper/releases/tag/2.4.5)
