### ISSUE TITLE
facing location problem when scraping person

### ISSUE THREAD

**Issue by survien** [joeyism/linkedin_scraper#34]
When I run this code
```
from linkedin_scraper import Person, actions, Company
from selenium import webdriver
driver = webdriver.Chrome()
email = "my email"
password = "my password"
actions.login(driver, email, password) 
person = Person("https://www.linkedin.com/in/andre-iguodala-65b48ab5",driver=driver)
```
It comes back
```
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".pv-top-card-v3"}
```

Maybe linkedin has upgrade their website

**Comment by joeyism** [comment]
Fixed and published in [2.4.3](https://github.com/joeyism/linkedin_scraper/releases/tag/2.4.3)

**Comment by maorkavod** [comment]
it happened to me in my test with this package. i think these problems are because linkedin had changed some UI changes on their website.

**Comment by ngillani** [comment]
Hello!  Hope you're well.  Running into this same issue in version 2.7.5 for a different profile ... it was able to succesfully scrape it once but seems to fail other times.  I wonder if a longer wait time is needed to let the page finish loading (and maybe then the element will be rendered?)

**Comment by joeyism** [comment]
Hi @ngillani , i just released a new version. Try it and let me know
