### ISSUE TITLE
How to scrape list of urls

### ISSUE THREAD

**Issue by ueembio** [joeyism/linkedin_scraper#35]
Hi I am trying to scrape linkedin profiles , i have urls of profile 
for l in link:
        try:
            person = Person(l, driver=driver, scrape=False)
            person.scrape(close_on_complete=False)
But every time i am receiving same profile , what's the issue

**Comment by joeyism** [comment]
are you appending `person` to a list? because if you just do
```python
for l in link:
    person = Person(l, driver=driver, scrape=False)
    person.scrape(close_on_complete=False)
print(person)
```
only the last person will be saved

**Comment by AnirudraChoudhury** [comment]
Hi @joeyism  you are right only the last person will be saved. @ueembio If you can try the follwing code you will have the profiles in a list.
```
# Declare output list
ProfileList = []
for l in link:
    person = Person(l, driver=driver, scrape=False)
    person.scrape(close_on_complete=False)
    ProfileList.append(person)  # Appending each profile in profile list

# looping through the profiles
for Profile in ProfileList:
    # you can do whatever you wants to with each profile
    print(Profile)
```

**Comment by wangheer2010** [comment]
Can we turn the profile objects to a better format? For example, how can we change it to a data frame?

**Comment by joeyism** [comment]
@wangheer2010 that's just data manipulation. Depending on what you want, you can extract out something like

```python
import pandas as pd
df = pd.DataFrame(
  data=[(profile.name, profile.linkedin_url, profile.education) for profile in profile_list],
  columns=["name", "url", "education"]
)
```
