### ISSUE TITLE
Error: "export CHROMEDRIVER=~/chromedriver"

### ISSUE THREAD

**Issue by Ledgrev** [joeyism/linkedin_scraper#38]
Hello,

I'm trying to run this in Jupyter Notebooks. When I enter "export CHROMEDRIVER=~/chromedriver" in an cell and run it, I get the following error message: 

`export CHROMEDRIVER=~/chromedriver
  File "<ipython-input-1-f9de4c739fa9>", line 1
    export CHROMEDRIVER=~/chromedriver
                      ^
SyntaxError: invalid syntax`

Could someone help me solve this? Please keep in mind that I am new to this. Thank you in advance!

**Comment by joeyism** [comment]
```bash
export CHROMEDRIVER=~/chromedriver
```
is a bash command. Jupyter takes python. In order to run this in Jupyter, you need to run it as a bash command with

```python
!export CHROMEDRIVER=~/chromedriver
```
