### ISSUE TITLE
[Feature]: Current company

### ISSUE THREAD

**Issue by ernests** [joeyism/linkedin_scraper#4]
Explicitly knowing company name allows me to go and find people at https://www.linkedin.com/title/[marketing]-at-[company-name]. Very valuable endpoint.

**Comment by joeyism** [comment]
Can you give me an example of what [marketing] and [company-name] is?

**Comment by ernests** [comment]
Sure:
https://www.linkedin.com/title/marketing-at-lego

**Comment by joeyism** [comment]
@ernests 
Is the [company-name] the same as company.name then?
