### ISSUE TITLE
Only name and surname scraped?

### ISSUE THREAD

**Issue by tchwpkgorg** [joeyism/linkedin_scraper#42]
Maybe I'm using it wrong, but I wasn't able to retrieve more info than person's name and surname.

Code used:

```
from linkedin_scraper import Person, actions
from selenium import webdriver
driver = webdriver.Chrome()

email = "my-login"
password = "my-pass"
actions.login(driver, email, password)
person = Person("https://www.linkedin.com/in/rbranson/", driver=driver, scrape=False)
person.scrape(close_on_complete=True)
print(person)
```

It prints out just:

```
Richard Branson

Experience
[b'Founder' at None from None to None for None based at None]

Education
[]

Interest
[]

Accomplishments
[]
```

Do I access the data in a wrong way?

**Comment by liyanasahir** [comment]
Same issue here! Do let me know if you've figured something out.

**Comment by AnirudraChoudhury** [comment]
Hi @tchwpkgorg 

As LinkedIn page structure i updated i am working on updating the code. @joeyism please assign the issue to me.

**Comment by AnirudraChoudhury** [comment]
Thanks @joeyism  I already make it able to read company name. I am working on the time.

**Comment by AnirudraChoudhury** [comment]
Hi @tchwpkgorg you can try the new version now. Thank you @joeyism for accepting my updates. You can resolve this issue now. This is my first contribution to open source project. Nice to work with you.
