### ISSUE TITLE
After installing linkedin_scraper, module still cannot be found

### ISSUE THREAD

**Issue by tanyingxiang** [joeyism/linkedin_scraper#51]
Hi, I tried installing the linkedin_scraper "!pip install linkedin_scraper" 
and tried to run your sample code but this error keeps coming up "ModuleNotFoundError: No module named 'linkedin_scraper'" is the a step which I have missed?

**Comment by joeyism** [comment]
can you give more details on how you're doing this? Judging from your code, I'm assuming you're using jupyter-notebook? If so, you can run
```bash
!pip3 install linkedin_scraper
```
```python
from linkedin_scraper import Person, actions
from selenium import webdriver
driver = webdriver.Chrome()

email = "some-email@email.address"
password = "password123"
actions.login(driver, email, password) # if email and password isnt given, it'll prompt in terminal
person = Person("https://www.linkedin.com/in/andre-iguodala-65b48ab5", driver=driver)
```
