### ISSUE TITLE
IndexError: list index out of range - Company Scraper Issues

### ISSUE THREAD

**Issue by mohitag09** [joeyism/linkedin_scraper#53]
#Wrote this basic code to scrape the company profile
from selenium import webdriver
from linkedin_scraper import Company,Person, actions
from IPython.core.debugger import set_trace
import time
driver=webdriver.Chrome(executable_path=r"C:\bin\chromedriver.exe")
#driver.get('http://www.google.com')
email = "<USERNAME>"
password = "<PASSWORD>"
actions.login(driver, email, password) # if email and password isnt given, it'll prompt in terminal
company = Company("https://www.linkedin.com/company/infosys",driver=driver)
print(company)

Getting "IndexError: list index out of range" error in the following line:
navigation.find_elements_by_xpath("//a[@data-control-name='page_member_main_nav_about_tab']")[0].click()
Any help please to fix the same?

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-41-efee0d0852f4> in <module>
     10 #person = Person("https://www.linkedin.com/in/mohitagarwal/", driver=driver, scrape=False)
     11 #person.scrape(close_on_complete=True)
---> 12 company = Company("https://www.linkedin.com/company/infosys",driver=driver)
     13 print(company)
     14 #set_trace()

~\AppData\Roaming\Python\Python38\site-packages\linkedin_scraper\company.py in __init__(self, linkedin_url, name, about_us, website, headquarters, founded, company_type, company_size, specialties, showcase_pages, affiliated_companies, driver, scrape, get_employees, close_on_complete)
     67 
     68         if scrape:
---> 69             self.scrape(get_employees=get_employees, close_on_complete=close_on_complete)
     70 
     71     def __get_text_under_subtitle(self, elem):

~\AppData\Roaming\Python\Python38\site-packages\linkedin_scraper\company.py in scrape(self, get_employees, close_on_complete)
     77     def scrape(self, get_employees = True, close_on_complete = True):
     78         if self.is_signed_in():
---> 79             self.scrape_logged_in(get_employees = get_employees, close_on_complete = close_on_complete)
     80         else:
     81             self.scrape_not_logged_in(get_employees = get_employees, close_on_complete = close_on_complete)

~\AppData\Roaming\Python\Python38\site-packages\linkedin_scraper\company.py in scrape_logged_in(self, get_employees, close_on_complete)
    146 
    147         self.name = driver.find_element_by_xpath('//span[@dir="ltr"]').text.strip()
--> 148         navigation.find_elements_by_xpath("//a[@data-control-name='page_member_main_nav_about_tab']")[0].click()
    149 
    150         _ = WebDriverWait(driver, 3).until(EC.presence_of_all_elements_located((By.TAG_NAME, 'section')))

IndexError: list index out of range

**Comment by mohitag09** [comment]
from selenium import webdriver
from linkedin_scraper import Company,Person, actions
from IPython.core.debugger import set_trace
import time
driver=webdriver.Chrome(executable_path=r"C:\bin\chromedriver.exe")
#driver.get('http://www.google.com')
email = ""
password = ""
actions.login(driver, email, password) # if email and password isnt given, it'll prompt in terminal
#person = Person("https://www.linkedin.com/in/mohitagarwal/", driver=driver, scrape=False)
#person.scrape(close_on_complete=True)
company = Company("https://www.linkedin.com/company/infosys",driver=driver)
print(company)

Getting "IndexError: list index out of range" error in the following line:
navigation.find_elements_by_xpath("//a[@data-control-name='page_member_main_nav_about_tab']")[0].click()

**Comment by lxuis97** [comment]
Same problem, I got this error message : 

Traceback (most recent call last):
  File "linkedin_search.py", line 56, in <module>
    lk_get_company_info('https://www.linkedin.com/company/sicara/')
  File "linkedin_search.py", line 34, in lk_get_company_info
    company.scrape(close_on_complete=False, get_employees=True)
  File "/Users/Louis/Library/Python/3.8/lib/python/site-packages/linkedin_scraper/company.py", line 79, in scrape
    self.scrape_logged_in(get_employees = get_employees, close_on_complete = close_on_complete)
  File "/Users/Louis/Library/Python/3.8/lib/python/site-packages/linkedin_scraper/company.py", line 148, in scrape_logged_in
    **navigation.find_elements_by_xpath("//a[@data-control-name='page_member_main_nav_about_tab']")[0].click()
IndexError: list index out of range**

**Comment by joeyism** [comment]
I just pushed a fix. Try version [2.5.2](https://github.com/joeyism/linkedin_scraper/releases/tag/2.5.2)

**Comment by mohitag09** [comment]
Using the fix, getting following error. 

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-10-1fef8da42f7f> in <module>
---> 12 company = Company(linkedin_url = "https://www.linkedin.com/company/google",driver=driver,close_on_complete=False,get_employees=False)
     13 set_trace()
     14 print(company)

~\AppData\Roaming\Python\Python38\site-packages\linkedin_scraper\company.py in __init__(self, linkedin_url, name, about_us, website, headquarters, founded, company_type, company_size, specialties, showcase_pages, affiliated_companies, driver, scrape, get_employees, close_on_complete)

~\AppData\Roaming\Python\Python38\site-packages\linkedin_scraper\company.py in scrape(self, get_employees, close_on_complete)

~\AppData\Roaming\Python\Python38\site-packages\linkedin_scraper\company.py in scrape_logged_in(self, get_employees, close_on_complete)

IndexError: list index out of range
