### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'click'

### ISSUE THREAD

**Issue by The-Winnster** [joeyism/linkedin_scraper#55]
![image](https://user-images.githubusercontent.com/71037838/92641584-32d71d80-f29c-11ea-8a7b-945ba84ba538.png)

Here is the screenshot of the code. I am trying to do a company scrape but it looks like when I search for 'page_member_main_nav_about_tab' after inspecting the HTML, it does not find anything with that tag name.  Any thoughts? Was running totally fine about 3 weeks ago, but perhaps something has since changed with LinkedIn's HTML structure.

**Comment by ehsong** [comment]
I had exactly the same problem when running the code.

**Comment by The-Winnster** [comment]
Anything I can do to help with the resolution? Happy to help with anything I can.

**Comment by EktaSangwan** [comment]
Any update ? I'm also getting None in both use cases(while scraping company as well as person)

**Comment by TrygviZL** [comment]
Just experienced the same.

**Comment by khalilkafrouni** [comment]
Any update on that issue? I'm getting this error as well.

**Comment by joeyism** [comment]
Fixed as of [2.5.4](https://github.com/joeyism/linkedin_scraper/releases/tag/2.5.4)
