### ISSUE TITLE
Not logging in 

### ISSUE THREAD

**Issue by isaacjoy** [joeyism/linkedin_scraper#58]
Hey there,

Just wondering, I tried the intro code for scraping a profile but the logging in does not working in headless chrome.

Is just adds my email + password and then hangs without submitting.

Appreciate any help.

Isaac

**Comment by isaacjoy** [comment]
Made a quick fix: https://github.com/joeyism/linkedin_scraper/pull/59

**Comment by joeyism** [comment]
Merged. You can use as of [2.5.4](https://github.com/joeyism/linkedin_scraper/releases/tag/2.5.4)

**Comment by joeyism** [comment]
Thanks for the fix
