### ISSUE TITLE
Company scraping blocked by authwall

### ISSUE THREAD

**Issue by bymi15** [joeyism/linkedin_scraper#61]
I'm trying to scrape LinkedIn public Company profile.
But on the first attempt, I get blocked by an authwall page: [https://www.linkedin.com/authwall?trk=gf...](https://www.linkedin.com/authwall?trk=gf...)
How can I bypass this authwall?

In the console I get the following exception:
`selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".name"}`

**Comment by joeyism** [comment]
https://github.com/joeyism/linkedin_scraper#scraping-sites-and-login-automatically
