### ISSUE TITLE
Crash when language is not set to english

### ISSUE THREAD

**Issue by cafehaine** [joeyism/linkedin_scraper#65]
Hi!
I've just started using your library and found a small bug.
I have my language set to french in linkedin, which means that the following lines couldn't extract anything:
https://github.com/joeyism/linkedin_scraper/blob/74a0bf6b0ea949ce4e5a41d06febae0d56a9045f/linkedin_scraper/company.py#L195-L210
This also meant that `self.industry` wasn't set to anything (no set to None like the other attributes in the class), so it crashed when `__repr__` was called (as I tried to print it).
Would you be interested in two PRs, one to add a warning about the display language used, and another one for the missing default value?
Thanks for reading :)

**Comment by joeyism** [comment]
Yea if you submit a MR, i'll take a look at it
