### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 80

### ISSUE THREAD

**Issue by xumengyan01** [joeyism/linkedin_scraper#69]
Hi, I tried with the test code, and it gives me a message that "Message: session not created: This version of ChromeDriver only supports Chrome version 80." Does it mean I have to downgrade my Chrome version? Thanks!

**Comment by gauravkr93** [comment]
Check the version of your google chrome and download the respective chrome driver version.

**Comment by joeyism** [comment]
Yea this error is specific to chrome and your version of chrome driver, independent from this project.
