### ISSUE TITLE
WebDriverException: Message: 'chromedriver' executable needs to be in PATH

### ISSUE THREAD

**Issue by kunalsharmagnome** [joeyism/linkedin_scraper#78]
yes i have set the CHROMEDRIVER variable
export CHROMEDRIVER=/home/rudrank/Documents/kunal/coderepo_up/kunalup/chromedriver_linux64

code i am trying to run is <company = Company(url)>

this is the issue :
#get information about comapny 
company = Company("https://www.linkedin.com/company/company_name/")
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~/anaconda3/envs/leadup/lib/python3.9/site-packages/selenium/webdriver/common/service.py in start(self)
     71             cmd.extend(self.command_line_args())
---> 72             self.process = subprocess.Popen(cmd, env=self.env,
     73                                             close_fds=platform.system() != 'Windows',

~/anaconda3/envs/leadup/lib/python3.9/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask)
    946 
--> 947             self._execute_child(args, executable, preexec_fn, close_fds,
    948                                 pass_fds, cwd, env,

~/anaconda3/envs/leadup/lib/python3.9/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid, gids, uid, umask, start_new_session)
   1818                         err_msg = os.strerror(errno_num)
-> 1819                     raise child_exception_type(errno_num, err_msg, err_filename)
   1820                 raise child_exception_type(err_msg)

FileNotFoundError: [Errno 2] No such file or directory: '/home/rudrank/anaconda3/envs/leadup/lib/python3.9/site-packages/linkedin_scraper/drivers/chromedriver'

During handling of the above exception, another exception occurred:

WebDriverException                        Traceback (most recent call last)
~/anaconda3/envs/leadup/lib/python3.9/site-packages/linkedin_scraper/company.py in __init__(self, linkedin_url, name, about_us, website, headquarters, founded, industry, company_type, company_size, specialties, showcase_pages, affiliated_companies, driver, scrape, get_employees, close_on_complete)
     65 
---> 66                 driver = webdriver.Chrome(driver_path)
     67             except:

~/anaconda3/envs/leadup/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py in __init__(self, executable_path, port, options, service_args, desired_capabilities, service_log_path, chrome_options, keep_alive)
     72             log_path=service_log_path)
---> 73         self.service.start()
     74 

~/anaconda3/envs/leadup/lib/python3.9/site-packages/selenium/webdriver/common/service.py in start(self)
     80             if err.errno == errno.ENOENT:
---> 81                 raise WebDriverException(
     82                     "'%s' executable needs to be in PATH. %s" % (

WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
~/anaconda3/envs/leadup/lib/python3.9/site-packages/selenium/webdriver/common/service.py in start(self)
     71             cmd.extend(self.command_line_args())
---> 72             self.process = subprocess.Popen(cmd, env=self.env,
     73                                             close_fds=platform.system() != 'Windows',

~/anaconda3/envs/leadup/lib/python3.9/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask)
    946 
--> 947             self._execute_child(args, executable, preexec_fn, close_fds,
    948                                 pass_fds, cwd, env,

~/anaconda3/envs/leadup/lib/python3.9/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid, gids, uid, umask, start_new_session)
   1818                         err_msg = os.strerror(errno_num)
-> 1819                     raise child_exception_type(errno_num, err_msg, err_filename)
   1820                 raise child_exception_type(err_msg)

FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'

During handling of the above exception, another exception occurred:

WebDriverException                        Traceback (most recent call last)
<ipython-input-24-7b6d8cf53ddd> in <module>
      1 #get information about comapny
----> 2 company = Company("https://www.linkedin.com/company/upticscrm/")

~/anaconda3/envs/leadup/lib/python3.9/site-packages/linkedin_scraper/company.py in __init__(self, linkedin_url, name, about_us, website, headquarters, founded, industry, company_type, company_size, specialties, showcase_pages, affiliated_companies, driver, scrape, get_employees, close_on_complete)
     66                 driver = webdriver.Chrome(driver_path)
     67             except:
---> 68                 driver = webdriver.Chrome()
     69 
     70         driver.get(linkedin_url)

~/anaconda3/envs/leadup/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py in __init__(self, executable_path, port, options, service_args, desired_capabilities, service_log_path, chrome_options, keep_alive)
     71             service_args=service_args,
     72             log_path=service_log_path)
---> 73         self.service.start()
     74 
     75         try:

~/anaconda3/envs/leadup/lib/python3.9/site-packages/selenium/webdriver/common/service.py in start(self)
     79         except OSError as err:
     80             if err.errno == errno.ENOENT:
---> 81                 raise WebDriverException(
     82                     "'%s' executable needs to be in PATH. %s" % (
     83                         os.path.basename(self.path), self.start_error_message)

WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by joeyism** [comment]
Try it with
```python
from selenium import webdriver
driver = webdriver.Chrome("/home/rudrank/Documents/kunal/coderepo_up/kunalup/chromedriver_linux64")
```
instead

Your problem now is strictly a chromedriver issue
