### ISSUE TITLE
Reset "person" Class attributes?

### ISSUE THREAD

**Issue by JulianAntonioMurillo** [joeyism/linkedin_scraper#84]
Hi, is there any way of resetting person class attributes so that when I run a for-loop to scrape multiple profiles I can reset attributes (job_title, experience, about, etc.)? Because right now when I scrape multiple profiles, it appends the last persons info to the next persons info in each column... eventually accumulating all profile information per column. Any help would be greatly appreciated. Thanks.

**Comment by joeyism** [comment]
Are you creating a new person object every time?

**Comment by JulianAntonioMurillo** [comment]
No, I'm trying to though. Code for for-loop below: 

for individual,link in contact_dict.items():

    ## assign ##
    the_name = individual
    the_link = link
    # scrape LinkedIn url's:
    person = Person(the_link, driver=driver, close_on_complete=False)

    # rows to be written in CSV
    rows = [[person.name, person.about, person.job_title, person.location, person.company,
             person.educations, person.accomplishments, person.linkedin_url]]
    # write
    with open('ScrapeResults.csv', 'a') as f:
        write = csv.writer(f)
        write.writerows(rows)
        f.close()

@joeyism 

Any help would be appreciated. I'm relatively new to Python and to Web Scraping. Thanks

**Comment by JulianAntonioMurillo** [comment]
I reinstalled version 2.7.5... same issue occurs? With list attributes such as person.about and person.educations... it appends all .about information for each person scraped in the for-loop.

![Installed](https://user-images.githubusercontent.com/61395774/110532512-c49bd800-80d1-11eb-9c33-9cc02e621445.png)
![Same Dilemma](https://user-images.githubusercontent.com/61395774/110532613-e9904b00-80d1-11eb-896f-61250cfa25ff.png)

**Comment by joeyism** [comment]
I can't reproduce your code because i don't have your list. This works for me though
```python
import os
from linkedin_scraper import Person, Company, actions
from selenium import webdriver
driver = webdriver.Chrome("./chromedriver")
actions.login(driver, os.getenv("LINKEDIN_USER"), os.getenv("LINKEDIN_PASSWORD"))
urls = ["https://www.linkedin.com/in/joey-sham-aa2a50122/", "https://www.linkedin.com/in/andre-iguodala-65b48ab5"]
persons = []
for url in urls:
    person = Person(url, driver=driver, close_on_complete=False)
    persons.append(person)

print(persons[0])
print(persons[1])
```

**Comment by JulianAntonioMurillo** [comment]
**Same Issue?**

I restarted my Python/PyCharm session after installing version 2.7.5:

![Terminal Output](https://user-images.githubusercontent.com/61395774/110571322-3e50b780-810c-11eb-8301-274d3f98e661.png)


Still getting the same output: For list attributes it still appends/accumulates all persons information.

![Same issue?](https://user-images.githubusercontent.com/61395774/110571514-79eb8180-810c-11eb-8cb6-07bb21d1fbce.png)


Code: 

```
# Import libraries
from linkedin_scraper import Person, Company, actions
from selenium import webdriver
import csv
import os
import pandas as pd
import numpy as np
import smtplib

# automatically login to LinkedIn
driver = webdriver.Chrome('./chromedriver')
email = os.environ.get('LINKEDIN_USER')
password = os.environ.get('LINKEDIN_PASS')
actions.login(driver, email, password)


# loop-through and collect multiple scraped persons0.
contacts = pd.read_csv("./ContactList.csv")
urls = contacts['contact_url'].tolist()

persons = []
for url in urls:
    person = Person(url, driver=driver, close_on_complete=False)
    persons.append(person)

```

**Comment by joeyism** [comment]
Can you add your csv list?

**Comment by JulianAntonioMurillo** [comment]
Git won't let me upload .CSV... but .xlsx here: 
[ContactList.xlsx](https://github.com/joeyism/linkedin_scraper/files/6114973/ContactList.xlsx)

**Comment by joeyism** [comment]
Just paste the urls here and i'll reconstruct it

**Comment by JulianAntonioMurillo** [comment]
**Pasted Below:**

https://www.linkedin.com/in/nicole-yonan-579989140

https://www.linkedin.com/in/erin-fabian-7b671a13a

https://www.linkedin.com/in/makayla-orlandi-957366130

**Comment by joeyism** [comment]
This is what I did
```python
import os
from linkedin_scraper import Person, Company, actions
from selenium import webdriver
driver = webdriver.Chrome("./chromedriver")
actions.login(driver, os.getenv("LINKEDIN_USER"), os.getenv("LINKEDIN_PASSWORD"))
urls = [ "https://www.linkedin.com/in/nicole-yonan-579989140",
"https://www.linkedin.com/in/erin-fabian-7b671a13a",
"https://www.linkedin.com/in/makayla-orlandi-957366130",
]
persons = []
for url in urls:
    person = Person(url, driver=driver, close_on_complete=False)
    persons.append(person)
````
This is what I got
![Screenshot from 2021-03-10 13-13-50](https://user-images.githubusercontent.com/7503144/110627607-7b678900-81a2-11eb-933b-b8228442a264.png)

**Comment by JulianAntonioMurillo** [comment]
It worked!!! But for whatever reason it only works when I use Jupyter NoteBooks? Must be a configuration issue?? No idea. But thanks so much. I'm a HUGE fan of your work. Especially the https://nnnba.herokuapp.com/ project!!! So cool!! @joeyism

**Comment by JulianAntonioMurillo** [comment]
Thanks so much for your time. I will be sure to recommend close friends to your repositories and plug your profile/work.
