### ISSUE TITLE
letter f throws error when running the application

### ISSUE THREAD

**Issue by alexFranka** [joeyism/linkedin_scraper#85]
https://github.com/joeyism/linkedin_scraper/blob/e988acf4cad1f97c5958a7ab0f2507b797c9cc7c/linkedin_scraper/person.py#L191

**Comment by joeyism** [comment]
Are you on python 3.6+?

**Comment by alexFranka** [comment]
I was but then downgraded to python 2.7

**Comment by alexFranka** [comment]
Now that we're on topic, am I supposed to be able to run this in Python 3.6+? I tried to run this using version 3.9 as my interpreter and got a few errors, but if I use 2.7 the app runs fine

**Comment by joeyism** [comment]
What's the error you get in 3.9?

**Comment by alexFranka** [comment]
well what do you know... I deleted the previously added 3.9 interpreter and added it back and now it works, lol sorry false alarm
