### ISSUE TITLE
Not scraping the HQ Location

### ISSUE THREAD

**Issue by Lightmare2** [joeyism/linkedin_scraper#90]
Hi,

I'm using your code for my master thesis (thanks btw) to scrape certain information of media companies. I'm interested in the type ,location (HQ) and the amount of employees. I made a preliminary script based on your code to test out if it would work. 

I managed to scrape all the info that I need: Name, Type & size except for the headquarters. It returns "None" for the four companies that I tried. 

If I'm correct, the HQ on linkedin is for Al Jazeera Doha (Marked in red) right? Next to the type of company.
<img width="398" alt="HQ Example" src="https://user-images.githubusercontent.com/5202206/112998494-5f865000-916e-11eb-9a4b-544928722f63.png">

Is there something wrong in my code that it is not able to scrape that particular part? Would be very usefull if I'm able to scrape that part for my master thesis! Not sure what I'm doing wrong..

Thank you in advance!

My code:
```
import os
from linkedin_scraper import Person, Company, actions
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException
driver = webdriver.Chrome(executable_path=r"D:\Python\chromedriver_win32\chromedriver.exe")
#options = webdriver.Chrome(executable_path=r"D:\Python\chromedriver_win32\chromedriver.exe")
#options.add_experimental_option('excludeSwitches', ['enable-logging'])
#driver = webdriver.Chrome(options=options)

email = "Some email"
password= "Some password" #os.getenv("LINKEDIN_USER")
#password = #os.getenv("LINKEDIN_PASSWORD")
actions.login(driver, email, password) # if email and password isnt given, it'll prompt in terminal

urls = ["https://www.linkedin.com/company/indiatimes","https://www.linkedin.com/company/criticalhitnet/about/", "https://www.linkedin.com/company/enca/", "https://www.linkedin.com/company/aljazeera/"]
companies=[]  

for url in urls:
    company = Company(url, driver=driver, close_on_complete=False, get_employees=False)
    companies.append(company)
    
for company in companies:
    print(company.headquarters)
    print(company.name)
    print(company.company_type)
    print(company.company_size)
    #print(company.about_us)
```

**Comment by NLCas8** [comment]
Experiencing the same here. Let me know if you found a fix!

**Comment by Lightmare2** [comment]
Thank you Cas!
