### ISSUE TITLE
Cannot find item "profile-nav-item" after logging in

### ISSUE THREAD

**Issue by aradzekler** [joeyism/linkedin_scraper#97]
Tried `WebDriverWait(driver, randint(10, 15)).until(EC.presence_of_element_located((By.ID, "profile-nav-item")))` which gives the following error: `  File "C:\Users\User\anaconda3\envs\scraping_env_3_8\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:` and  
`time.sleep(5)
self.driver.find_element_by_id("profile-nav-item")` which giving me the following error: `selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="profile-nav-item"]"}
  (Session info: chrome=89.0.4389.128)`

**Comment by joeyism** [comment]
Try [2.8.2](https://github.com/joeyism/linkedin_scraper/releases/tag/2.8.2)

**Comment by aradzekler** [comment]
works! thank you so much!
