### ISSUE TITLE
Add Cookie capabilities 

### ISSUE THREAD

**Issue by fox895** [joeyism/linkedin_scraper#99]
I really like this package but passing my email and password to a script it's not ideal in my mind.
I know that I can load them using environmental variable but I still think there are better ways.
Other packages have the abilities to pass the LI_AT cookies to the selenium driver thus avoiding the necessary login procedure.

Could be a nice feature to let the user decide to use either the login form with email and password or the LI_AT cookie trick.

**Comment by joeyism** [comment]
That's a good point. If you know how to pass it, maybe you can help me or just submit a PR and I'll take a look at it

**Comment by fox895** [comment]
I haven't check your code in details, but when you create the selenium driver/browser you can do:
`
driver.add_cookie({
                'name': 'li_at',
                'value': li_tat_cookie_value,
                'domain': '.linkedin.com'
            })
`

Only point is I believe you have to inject this cookie after visiting LinkedIn a first time...
